name: Continuous Deployment

on:
  push:
    branches: [main]

env:
  DATABASE_URL: postgresql://postgres:Jesus33..@localhost:5432/products-api?schema=public
  

jobs:
  deploy-to-production:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code and add it to CI server
        uses: actions/checkout@v2
      
      - name: Setup heroku deploy action
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "product-api-onlineshoppingapp"
          heroku_email: "kire5brenda@gmail.com"